add Key patch request to transfer to new key ring
IBM/keyprotect-go-client pull request #59
Opened 2021-03-24 17:19 UTC by gspurthi

Associated with the issue: 473

Changes included in the PR: 
```
Added method TransferKeytoNewKeyRing
Updated unit tests for the method and the key structure change.
Fixed bug where the imported field is not shown in the response when false.
```

2021-03-24 20:42 UTC, pbavari commented on keys.go
> +	keyRingRequestBody := KeyRingID{
Validate keyID and newKeyRingID is valid string

2021-03-24 20:56 UTC, mrodden requested changes

2021-03-24 20:56 UTC, mrodden commented on keys.go
> +func (c *Client) TransferKeyToNewKeyRing(ctx context.Context, keyID, newKeyRingID string) (*Key, error) {
This is more of a `SetKeyRing` honestly. It will always put the new value so its a set.

2021-03-25 18:59 UTC, pbavari requested changes

2021-03-25 18:59 UTC, pbavari commented on kp_test.go
> +func TestTransferKeyToNewKeyRing(t *testing.T) {
Change this to match actual method name

2021-03-25 18:59 UTC, pbavari commented on kp_test.go
> +	key, err := c.TransferKeyToNewKeyRing(context.Background(), keyID, newKeyRingID)
this should have not worked after changing method name.

2021-03-25 22:42 UTC, mrodden approved these changes

2021-03-25 22:42 UTC, mrodden commented on keys.go
> +	}
Nice.

2021-03-30 18:52 UTC, pbavari approved these changes

2021-03-31 15:41 UTC, merged