Alias Extension
IBM/keyprotect-go-client pull request #79
Opened 2022-05-26 07:05 UTC by harshit777

Alias Suppport functionality

2022-05-26 07:09 UTC, harshit777 commented
![Go-SDK integration test](https://user-images.githubusercontent.com/25618813/170436722-b5364a5e-7e69-4b89-bd26-49b1c2ac53c7.jpeg)

2022-05-26 10:51 UTC, dinesh-venkatraman-g requested changes

2022-05-26 10:51 UTC, dinesh-venkatraman-g commented on integration_test.go
> +}
Let's delete the key once the tests are done

2022-05-26 10:51 UTC, dinesh-venkatraman-g commented on example_test.go
> +func ExampleClient_WrapCreateDEKWithAlias() {
We should add ExampleClient_WrapCreateKeyAlias() and ExampleClient_WrapCreateDEKWithAlias() & ExampleClient_UnWrapCreateDEKWithAlias()

2022-05-26 12:50 UTC, harshit777 commented
![Updated SDK test cases](https://user-images.githubusercontent.com/25618813/170490924-525a9fa5-6863-4684-bd17-c9d510a8af6b.jpeg)

2022-05-26 12:56 UTC, harshit777 commented
![Updated SDK test cases](https://user-images.githubusercontent.com/25618813/170491840-8927db44-dbda-44b9-a79e-9b7a5e3042d1.jpeg)

![Updated SDK test cases](https://user-images.githubusercontent.com/25618813/170491865-e80e70b2-5d70-4cb8-b88c-f7bf2e8d56ec.jpeg)

2022-05-26 13:03 UTC, harshit777 commented
![Updated SDK test cases](https://user-images.githubusercontent.com/25618813/170493014-4512c267-3628-4c9e-baf2-4fbf4bb9501c.jpeg)

![Updated SDK test cases](https://user-images.githubusercontent.com/25618813/170493048-fe9f318e-a98d-452c-ab71-620b80fceed0.jpeg)

2022-05-26 15:00 UTC, dinesh-venkatraman-g approved these changes

2022-05-26 15:22 UTC, harshit777 commented
<details open>
<summary>go test -v -tags=integration ./... </summary>
<br>
=== RUN   TestWrapUnwrap
    integration_test.go:81: {ID:0d7c18bb-2558-473b-974b-faf91cf71401 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-10 16:01:43 +0000 UTC LastUpdateDate:2022-02-10 16:01:43 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:0d7c18bb-2558-473b-974b-faf91cf71401 EncryptedNonce: IV: Deleted:0xc00001f71b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010158}
    integration_test.go:81: {ID:12da8e3c-ef58-4b5c-8c98-a8cc239a85ce Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-16 09:15:45 +0000 UTC LastUpdateDate:2022-02-16 09:15:45 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:12da8e3c-ef58-4b5c-8c98-a8cc239a85ce EncryptedNonce: IV: Deleted:0xc00001f73b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010160}
    integration_test.go:81: {ID:16c5fac3-9bce-4c25-b920-817baf1ee265 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-16 09:40:06 +0000 UTC LastUpdateDate:2022-02-16 09:40:06 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:16c5fac3-9bce-4c25-b920-817baf1ee265 EncryptedNonce: IV: Deleted:0xc00001f75b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010168}
    integration_test.go:81: {ID:17356455-5acb-475c-a021-e7904c01f350 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-05-26 03:24:31 +0000 UTC LastUpdateDate:2022-05-26 03:24:31 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:17356455-5acb-475c-a021-e7904c01f350 EncryptedNonce: IV: Deleted:0xc00001f77b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010170}
    integration_test.go:81: {ID:36f42252-fac0-494e-a2a2-27ccce55c8cb Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-16 07:05:03 +0000 UTC LastUpdateDate:2022-02-16 07:05:03 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:36f42252-fac0-494e-a2a2-27ccce55c8cb EncryptedNonce: IV: Deleted:0xc00001f79b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010178}
    integration_test.go:81: {ID:3d120be1-fab1-437f-b0d6-fed174c43c20 Name:MyRootKey Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-02 10:56:12 +0000 UTC LastUpdateDate:2022-02-09 14:47:09 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000eac8 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:2 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:3d120be1-fab1-437f-b0d6-fed174c43c20 EncryptedNonce: IV: Deleted:0xc00001f7d4 DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010180}
    integration_test.go:81: {ID:3e7430bb-b5ce-4d65-8675-1545b871afcc Name:MyRootKey Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-02 10:50:25 +0000 UTC LastUpdateDate:2022-02-02 10:50:25 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000eb40 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:3e7430bb-b5ce-4d65-8675-1545b871afcc EncryptedNonce: IV: Deleted:0xc00001f7eb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010188}
    integration_test.go:81: {ID:40da6037-8bf1-41e2-a263-a71507d040a9 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-16 09:17:03 +0000 UTC LastUpdateDate:2022-02-16 09:17:03 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:40da6037-8bf1-41e2-a263-a71507d040a9 EncryptedNonce: IV: Deleted:0xc00001f80b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010190}
    integration_test.go:81: {ID:4255d608-a3a2-44ef-87bc-2c68c2f54958 Name:TEST12345 Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-02-10 15:57:32 +0000 UTC LastUpdateDate:2022-02-10 15:57:32 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000ebd0 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:4255d608-a3a2-44ef-87bc-2c68c2f54958 EncryptedNonce: IV: Deleted:0xc00001f844 DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010198}
    integration_test.go:81: {ID:4415922b-a95a-491d-8e92-9c5e81fe0c56 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-05-26 12:48:40 +0000 UTC LastUpdateDate:2022-05-26 12:48:40 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/f74a5121f36e48f28d994399e4536f0b:57e70812-8c3e-4b44-98fa-06ad25941dda:key:4415922b-a95a-491d-8e92-9c5e81fe0c56 EncryptedNonce: IV: Deleted:0xc00001f860 DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101a0}
    integration_test.go:81: {ID:4606ce1d-57e4-450c-a8eb-a18497f29dfb Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-55000A1NKE CreationDate:2022-05-26 03:31:47 +0000 UTC LastUpdateDate:2022-05-26 03:31:47 +0000 U [...]

2022-05-26 15:38 UTC, harshit777 commented
![Updated unwrap](https://user-images.githubusercontent.com/25618813/170522696-4862d2d9-1882-4ac4-9d0e-f244ad77e484.jpeg)

![Updated unwrap](https://user-images.githubusercontent.com/25618813/170522734-6912d9fc-838a-42d2-bc2c-b7190df355f4.jpeg)

2022-06-16 01:17 UTC, mrodden requested changes
Small cleanup of some of the commented out asserts in tests. Looks like they were intended to be removed.

2022-06-16 01:17 UTC, mrodden commented on kp_test.go
> +	// assert.Contains(t, key.Aliases, alias)
Seems like this needs cleanup

2022-06-23 16:34 UTC, mrodden approved these changes

2022-06-23 16:34 UTC, merged