Listkey new filter
IBM/keyprotect-go-client pull request #96
Opened 2022-09-28 11:34 UTC by Rishi-web

W.r.t issue - https://github.ibm.com/kms/kmk/issues/1300

Supporting the list keys with new filter properties.

2022-09-28 11:54 UTC, Rishi-web commented
Kp-test cases 

<img width="1369" alt="Screenshot 2022-09-28 at 5 23 53 PM" src="https://user-images.githubusercontent.com/68048332/192772445-17f31e5f-cdb2-4397-88c5-0f1481dd3c0d.png">

2022-09-28 11:56 UTC, Rishi-web commented
<details>
<summary> Integration test case </summary>
rushil@Rushils-MacBook-Pro keyprotect-go-client % go test -v -tags=integration ./...
=== RUN   TestWrapUnwrap
    integration_test.go:81: {ID:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:22:49 +0000 UTC LastUpdateDate:2022-09-28 11:22:49 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 EncryptedNonce: IV: Deleted:0xc0002196ab DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000206168 Rotation:<nil>}
    integration_test.go:81: {ID:9180917c-41c5-4b4e-98b1-fcc63e49ae55 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:11:35 +0000 UTC LastUpdateDate:2022-09-28 11:11:35 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:9180917c-41c5-4b4e-98b1-fcc63e49ae55 EncryptedNonce: IV: Deleted:0xc0002196cb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000206170 Rotation:<nil>}
    integration_test.go:81: {ID:dda64755-fcba-46a0-b6f2-0c214b98d404 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:19:25 +0000 UTC LastUpdateDate:2022-09-28 11:19:25 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:dda64755-fcba-46a0-b6f2-0c214b98d404 EncryptedNonce: IV: Deleted:0xc0002196eb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000206178 Rotation:<nil>}
    integration_test.go:86: CRK created successfully: id=066828ab-7345-4b8e-a696-4da3f364c6d8
    integration_test.go:103: Key deleted: id=066828ab-7345-4b8e-a696-4da3f364c6d8
--- PASS: TestWrapUnwrap (10.06s)
=== RUN   TestWrapUnwrapWithAlias
    integration_test.go:118: CRK created successfully: id=98fe5687-74e2-4c27-a117-ac2e2869ebb8
    integration_test.go:122: CRK Alias created successfully: id=&{98fe5687-74e2-4c27-a117-ac2e2869ebb8 myaliasnew123 IBMid-665000G2B5 2022-09-28 11:53:37 +0000 UTC}
    integration_test.go:126: Get Key successfully: id=98fe5687-74e2-4c27-a117-ac2e2869ebb8
--- PASS: TestWrapUnwrapWithAlias (7.37s)
=== RUN   TestRotatedKeyHasLastUpdatedAndRotated
    integration_test.go:151: {ID:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:22:49 +0000 UTC LastUpdateDate:2022-09-28 11:22:49 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 EncryptedNonce: IV: Deleted:0xc000019ccb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010208 Rotation:<nil>}
    integration_test.go:151: {ID:9180917c-41c5-4b4e-98b1-fcc63e49ae55 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:11:35 +0000 UTC LastUpdateDate:2022-09-28 11:11:35 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:9180917c-41c5-4b4e-98b1-fcc63e49ae55 EncryptedNonce: IV: Deleted:0xc000019ceb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010210 Rotation:<nil>}
    integration_test.go:151: {ID:dda64755-fcba-46a0-b6f2-0c214b98d404 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:19:25 +0000 UTC LastUpdateDate:2022-09-28 11:19:25 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:dda64755-fcba-46a0-b6f2-0c214b98d404 EncryptedNonce: IV: Deleted:0xc000019d0b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010218 Rotation:<nil>}
    integration_test.go:156: CRK created successfully: id=28da3db2-1f1e-4181-a096-5049c32dcf5d
    integration_test.go:163: CRK rotated successfully: id=28da3db2-1f1e-4181-a096-5049c32dcf5d
    integration_test.go:179: Key deleted: id=28da3db2-1f1e-4181-a096-5049c32dcf5d
--- PASS: TestRotatedKeyHasLastUpdatedAndRotated (6.69s)
=== RUN   TestExtractableKey
    integration_test.go:203: {ID:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:22:49 +0000 UTC LastUpdateDate:2022-09-28 11:22:49 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:4b9cb85f-f0a7-4788-8366-a70e6bba7d60 EncryptedNonce: IV: Deleted:0xc00040808b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000206008 Rotation:<nil>}
    integration_test.go:203: {ID:9180917c-41c5-4b4e-98b1-fcc63e49ae55 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:11:35 +0000 UTC LastUpdateDate:2022-09-28 11:11:35 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:9180917c-41c5-4b4e-98b1-fcc63e49ae55 EncryptedNonce: IV: Deleted:0xc0004080ab DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000206010 Rotation:<nil>}
    integration_test.go:203: {ID:dda64755-fcba-46a0-b6f2-0c214b98d404 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-28 11:19:25 +0000 UTC LastUpdateDate:2022-09-28 11:19:25 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:698a2c40-6aaa-4414-a1ca-3cd56556c9bf:key:dda64755-fcba-46a0-b6f2-0 [...]

2022-09-30 08:57 UTC, Rishi-web commented
<details>
<summary> Integration test </summary>
rushil@Rushils-MBP keyprotect-go-client % go test -v -tags=integration ./...
=== RUN   TestWrapUnwrap
    integration_test.go:83: {ID:009e6b16-d516-4956-b706-4cc047666005 Name:root-key3 Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-05-25 08:56:55 +0000 UTC LastUpdateDate:2022-05-25 08:56:55 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000e948 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:009e6b16-d516-4956-b706-4cc047666005 EncryptedNonce: IV: Deleted:0xc00001975b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010178 Rotation:<nil>}
    integration_test.go:83: {ID:11f6fa8c-a655-4708-978d-f0aa13fced91 Name:Another generated key Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-08-09 10:05:21 +0000 UTC LastUpdateDate:2022-08-09 10:05:21 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000e9a8 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:11f6fa8c-a655-4708-978d-f0aa13fced91 EncryptedNonce: IV: Deleted:0xc00001977b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010180 Rotation:<nil>}
    integration_test.go:83: {ID:1757283d-fc6b-4a40-9615-be548b85b08f Name:test_filter_key_retrieval_standard Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-08-10 12:48:30 +0000 UTC LastUpdateDate:2022-08-10 12:48:30 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:1757283d-fc6b-4a40-9615-be548b85b08f EncryptedNonce: IV: Deleted:0xc00001979b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010188 Rotation:<nil>}
    integration_test.go:83: {ID:1a16f971-7176-460f-9506-abd9dfac13cc Name:test2_standard Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-07-13 11:27:10 +0000 UTC LastUpdateDate:2022-07-13 11:27:10 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:1a16f971-7176-460f-9506-abd9dfac13cc EncryptedNonce: IV: Deleted:0xc0000197cb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010190 Rotation:<nil>}
    integration_test.go:83: {ID:1b205a9e-af94-488d-8057-d1bc67dca36c Name:test_filter_key_retrieval_root Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-08-09 12:39:17 +0000 UTC LastUpdateDate:2022-08-09 12:39:17 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000ea80 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:1b205a9e-af94-488d-8057-d1bc67dca36c EncryptedNonce: IV: Deleted:0xc0000197eb DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc000010198 Rotation:<nil>}
    integration_test.go:83: {ID:263dda60-bc24-4177-a3dd-032ea6593e81 Name:name Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-05-27 09:58:38 +0000 UTC LastUpdateDate:2022-05-27 09:58:38 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000eae0 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:263dda60-bc24-4177-a3dd-032ea6593e81 EncryptedNonce: IV: Deleted:0xc00001980b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101a0 Rotation:<nil>}
    integration_test.go:83: {ID:3074ecac-99f9-4e56-ab4f-ce960e4c1980 Name:standard-key1 Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-05-25 08:57:10 +0000 UTC LastUpdateDate:2022-05-25 08:57:10 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:3074ecac-99f9-4e56-ab4f-ce960e4c1980 EncryptedNonce: IV: Deleted:0xc00001983b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101a8 Rotation:<nil>}
    integration_test.go:83: {ID:3292fc83-d4d0-42cf-8bb1-0eab6d1ef4f1 Name:standard-key3 Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-05-25 08:57:25 +0000 UTC LastUpdateDate:2022-05-25 08:57:25 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:3292fc83-d4d0-42cf-8bb1-0eab6d1ef4f1 EncryptedNonce: IV: Deleted:0xc00001986b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101b0 Rotation:<nil>}
    integration_test.go:83: {ID:38d12744-77b6-4fcd-9034-509f00cdbe22 Name:kptest-extractable Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-09-30 08:46:20 +0000 UTC LastUpdateDate:2022-09-30 08:46:20 +0000 UTC LastRotateDate:<nil> KeyVersion:<nil> KeyRingID:default Extractable:true Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:38d12744-77b6-4fcd-9034-509f00cdbe22 EncryptedNonce: IV: Deleted:0xc00001988b DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101b8 Rotation:<nil>}
    integration_test.go:83: {ID:3cc1c3cc-f821-41bd-a73f-1c6ef8b0da6c Name:root-key1 Description: Type:application/vnd.ibm.kms.key+json Tags:[] Aliases:[] AlgorithmType:AES CreatedBy:IBMid-665000G2B5 CreationDate:2022-05-25 08:56:43 +0000 UTC LastUpdateDate:2022-05-25 08:56:43 +0000 UTC LastRotateDate:<nil> KeyVersion:0xc00000ec00 KeyRingID:default Extractable:false Expiration:<nil> Imported:false Payload: State:1 EncryptionAlgorithm: CRN:crn:v1:bluemix:public:kms:us-south:a/2f157e042ac646c689d990e991e51eff:6e8ba383-6ad2-47e8-abfc-4cf7a086439e:key:3cc1c3cc-f821-41bd-a73f-1c6ef8b0da6c EncryptedNonce: IV: Deleted:0xc0000198c4 DeletedBy:<nil> DeletionDate:<nil> PurgeAllowed:<nil> PurgeAllowedFrom:<nil> PurgeScheduledOn:<nil> DualAuthDelete:0xc0000101c0 Rotation:<nil>}
    integration_test.go:83: {ID:3f7e1d75-3807-4265-918c-9cc096777 [...]

2022-09-30 08:58 UTC, Rishi-web commented
Unit test case

<img width="1361" alt="Screenshot 2022-09-30 at 2 28 24 PM" src="https://user-images.githubusercontent.com/68048332/193233693-48a1334d-5ac1-47bc-b5c9-24856a3aa793.png">

2022-09-30 10:09 UTC, dinesh-venkatraman-g requested changes
- Attach detect secrets report 
- Readme to be updated with example - Give example for both options

2022-09-30 11:02 UTC, Rishi-web commented
Detect secrets 

<img width="908" alt="Screenshot 2022-09-30 at 4 32 27 PM" src="https://user-images.githubusercontent.com/68048332/193256244-08b3b3b7-e4e1-437d-b0e7-23a218a74cba.png">

2022-10-03 06:53 UTC, dinesh-venkatraman-g requested changes

2022-10-03 06:53 UTC, dinesh-venkatraman-g commented on listkeys.go
> +// Filter
```suggestion
```

2022-10-03 06:53 UTC, dinesh-venkatraman-g commented on listkeys.go
> +// filter related funcs
```suggestion
// Filter related functions
```

2022-10-03 06:53 UTC, dinesh-venkatraman-g commented on README.md
> +// Option-1 - Directly building the filter query which API supports.
```suggestion
// Option-1 - Directly passing the filter query string which the API supports.
```

2022-10-03 06:53 UTC, dinesh-venkatraman-g commented on README.md
> +// Option-2 - By using builder pattern approach
```suggestion
// Option-2 - Using the builder provided by SDK to construct the filter query 
```

2022-10-03 11:39 UTC, dinesh-venkatraman-g commented on README.md
> +// Option-1 - Directly passing the filter query string which the API supports.
```suggestion
// Option-1 - Directly passing the filter query in the format that the API supports.
```

2022-10-03 12:09 UTC, dinesh-venkatraman-g approved these changes

2022-10-03 12:39 UTC, EktaBharti1998 commented
LGMT

2022-10-03 12:40 UTC, EktaBharti1998 approved these changes
LGTM

2022-10-06 07:13 UTC, merged