Latest go lang version
IBM/keyprotect-go-client pull request #97
Opened 2022-09-29 05:41 UTC by Rishi-web

w.r.t issue - https://github.ibm.com/kms/kmk/issues/1426

Upgrading go lang to latest version in travis.yml file

2022-09-29 06:01 UTC, Rishi-web commented
<img width="802" alt="Screenshot 2022-09-29 at 11 31 02 AM" src="https://user-images.githubusercontent.com/68048332/192951260-21616624-ecfa-412c-8563-621cca93393e.png">

2022-09-29 11:28 UTC, dinesh-venkatraman-g requested changes

2022-09-29 11:28 UTC, dinesh-venkatraman-g commented on .travis.yml
> + - 1.18.x
We should continue to support 1.14 & 1.15 as well

2022-09-29 11:35 UTC, Rishi-web commented
<img width="720" alt="Screenshot 2022-09-29 at 5 05 08 PM" src="https://user-images.githubusercontent.com/68048332/193021143-ffb4f2ca-41c3-4168-8556-b01c0cf07063.png">

2022-09-29 11:36 UTC, Rishi-web commented
<img width="656" alt="Screenshot 2022-09-29 at 5 05 59 PM" src="https://user-images.githubusercontent.com/68048332/193021303-ea921618-a8c3-4c03-91ce-c28ea5fb76cf.png">

2022-10-06 07:15 UTC, dinesh-venkatraman-g requested changes
Update the travis job to support support last 3 version of go lang.

2022-10-06 07:28 UTC, dinesh-venkatraman-g approved these changes

2022-10-06 07:29 UTC, merged